### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by mcansh — APPROVED** [review]

**Comment by kentcdodds** [comment]
Could we figure out the TypeScrip issue?

**Comment by MichaelDeBoey** [comment]
@kentcdodds Looking into it as we speak

**Comment by MichaelDeBoey** [comment]
@kentcdodds Should be fine now.

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Pull request merged**
