### PR TITLE
Add explicit function return types to session.server.tsx

### PR DESCRIPTION
**Pull request by Code42Cate**
Hey!

I was playing around with this stack and saw that only some functions have explicit return types in `session.server.tsx` so I added them.

Thanks for remix:)

### CODE REVIEW

**Review by mcansh — APPROVED** [review]

**Review by kentcdodds — COMMENTED** [review]
I'd prefer to go the other way and rely on type inference.

**Comment by Code42Cate** [comment]
I could also remove the unneeded types then if you want.

**Comment by kentcdodds** [comment]
That would be welcome 😁

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Pull request merged**
