### PR TITLE
chore: switch to toml-select github action

### PR DESCRIPTION
**Pull request by sravinet**
Quick improvement 
See https://github.com/marketplace/actions/toml-select-toml-field-extractor-action

### CODE REVIEW

**Comment by ryanhalliday** [comment]
Why on earth should this be changed to a package you control? It's not like the old one is out of date or doesn't get updates: https://github.com/SebRollen/toml-action

Is this some cybersec theatre?

**Comment by MichaelDeBoey** [comment]
Since your action is literally doing the same thing as the one we currently use, I don't see why we would change usage tbh.

**Comment by ryanhalliday** [comment]
I am not a maintainer, my opinions are my own. My harshness was to ensure this did not get merged without strong consideration as it has the potential to proliferate to a lot of projects.

Suggesting an open source project change to a package you maintain should come with much more explanation than "Quick improvement". I'm sure the contribution is appreciated but appears unnecessary in the current circumstances.

That's the last I'll say on this, sorry if my wording caused a minor headache maintainers.

**Comment by sravinet** [comment]
Sure. Thanks for the apology. Nothing was hidden Ryan. Link to full description was provided very start.

**Pull request closed without merging**
